---
- name: check if ant binary exists
  ansible.builtin.stat:
    path: "{{ binary_dir }}/ant"
  register: ant_binary

- name: download the ant binary
  ansible.builtin.get_url:
    url: "{{ ant_archive_url }}"
    dest: "/tmp/{{ ant_archive_filename }}"
  when: not ant_binary.stat.exists

- name: extract the ant binary to /usr/local/bin
  ansible.builtin.unarchive:
    src: "/tmp/{{ ant_archive_filename }}"
    dest: "{{ binary_dir }}"
    remote_src: true
  become: true
  when: not ant_binary.stat.exists

- name: check if ant group exists
  ansible.builtin.getent:
    database: group
    key: ant
  register: ant_group
  failed_when: false

- name: create ant group if it doesn't exist
  ansible.builtin.group:
    name: ant
    state: present
  become: true
  when: ant_group.ansible_facts.getent_group is not defined or ant_group.ansible_facts.getent_group.ant is not defined

- name: check if ant1 user exists
  ansible.builtin.getent:
    database: passwd
    key: ant1
  register: ant1_user
  failed_when: false

- name: create ant1 user if it doesn't exist
  ansible.builtin.user:
    name: ant1
    shell: /bin/bash
    group: ant
    state: present
  become: true
  when: ant1_user.ansible_facts.getent_passwd is not defined or ant1_user.ansible_facts.getent_passwd.ant1 is not defined

- name: check if chunk whitelist exists locally
  ansible.builtin.stat:
    path: "{{ role_path }}/files/chunk_whitelist.csv"
  delegate_to: localhost
  register: whitelist_file
  become: false

- name: copy chunk whitelist
  ansible.builtin.copy:
    src: chunk_whitelist.csv
    dest: "/home/ant1/chunk_whitelist.csv"
    owner: ant1
    group: ant
    mode: '0644'
  become: true
  become_user: ant1
  when: whitelist_file.stat.exists

- name: copy ant_scan_repair.sh to remote
  ansible.builtin.template:
    src: ant_scan_repair.sh.j2
    dest: "/home/ant1/ant_scan_repair.sh"
    owner: ant1
    group: ant
    mode: '0744'
  become: true
  become_user: ant1

- name: Check if systemd service file exists
  ansible.builtin.stat:
    path: "/etc/systemd/system/ant_scan_repair.service"
  register: service_file_stat

- name: copy ant_scan_repair service file
  ansible.builtin.template:
    src: ant_scan_repair.service.j2
    dest: "/etc/systemd/system/ant_scan_repair.service"
    owner: root
    group: root
    mode: '0644'
  become: true
  when: not service_file_stat.stat.exists

- name: reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes
  become: true

- name: enable ant_scan_repair service for each tracker
  ansible.builtin.systemd:
    name: "ant_scan_repair"
    enabled: yes
  become: true

- name: start ant_scan_repair service if requested
  ansible.builtin.systemd:
    name: "ant_scan_repair"
    state: started
  become: true
  when: start_repair_service | default(false) | bool
