---
- name: Run Step 1 tasks for full cone NAT gateway
  include_tasks: step1.yml
  when: action == "step1"

- name: Run Step 2 tasks for full cone NAT gateway
  include_tasks: step2.yml
  when: action == "step2"