---
- name: check if ant binary exists
  ansible.builtin.stat:
    path: "{{ binary_dir }}/ant"
  register: ant_binary

- name: download the ant binary
  ansible.builtin.get_url:
    url: "{{ ant_archive_url }}"
    dest: "/tmp/{{ ant_archive_filename }}"
  when: not ant_binary.stat.exists

- name: extract the ant binary to binary directory
  ansible.builtin.unarchive:
    src: "/tmp/{{ ant_archive_filename }}"
    dest: "{{ binary_dir }}"
    remote_src: true
  become: true
  when: not ant_binary.stat.exists

- name: create ant group
  ansible.builtin.group:
    name: ant
    state: present
  become: true

- name: create ant1 user
  ansible.builtin.user:
    name: ant1
    shell: /bin/bash
    group: ant
    state: present
  become: true

- name: copy ant_data_retrieval.py to remote
  ansible.builtin.template:
    src: ant_data_retrieval.py.j2
    dest: /home/ant1/ant_data_retrieval.py
    owner: ant1
    group: ant
    mode: '0775'
  become: true
  become_user: ant1

- name: ensure the ant users can write to the download directory
  ansible.builtin.file:
    path: "{{ downloads_dir_path }}"
    state: directory
    mode: '0775'
    owner: ant1
    group: ant
  become: true

- name: ensure the ant users can write to the log output destination
  ansible.builtin.file:
    path: "{{ log_output_dir_path }}"
    state: directory
    mode: '0775'
    owner: root
    group: ant
  become: true

- name: copy prod.csv file to remote server
  ansible.builtin.copy:
    src: prod.csv
    dest: /home/ant1/prod.csv
    owner: ant1
    group: ant
    mode: '0644'
  become: true

- name: copy manifests directory to remote server
  ansible.builtin.copy:
    src: manifests/
    dest: "{{ manifest_dir_path }}/"
    owner: root
    group: ant
    mode: '0644'
    directory_mode: '0755'
  become: true

- name: Check if systemd ant_data_retrieval service file exists
  ansible.builtin.stat:
    path: "/etc/systemd/system/ant_data_retrieval.service"
  register: ant_data_retrieval_stat

- name: create ant_data_retrieval systemd service file
  ansible.builtin.template:
    src: ant_data_retrieval.service.j2
    dest: "/etc/systemd/system/ant_data_retrieval.service"
    owner: ant1
    group: ant
    mode: '0644'
  become: true
  when: not ant_data_retrieval_stat.stat.exists

- name: enable ant_data_retrieval service
  ansible.builtin.systemd:
    name: ant_data_retrieval
    enabled: "{{ start_data_retrieval | default(false) | bool }}"
    daemon_reload: yes
  become: true

- name: start ant_data_retrieval service
  ansible.builtin.systemd:
    name: ant_data_retrieval
    state: started
  become: true
  when: start_data_retrieval | default(false) | bool
