---
- name: check if ant binary exists
  ansible.builtin.stat:
    path: "{{ binary_path }}/ant"
  register: ant_binary

- name: download the ant binary
  ansible.builtin.get_url:
    url: "{{ ant_archive_url }}"
    dest: "/tmp/{{ ant_archive_filename }}"
  when: not ant_binary.stat.exists

- name: extract the ant binary to binary directory
  ansible.builtin.unarchive:
    src: "/tmp/{{ ant_archive_filename }}"
    dest: "{{ binary_path }}"
    remote_src: true
  become: true
  when: not ant_binary.stat.exists

- name: create ant group
  ansible.builtin.group:
    name: ant
    state: present
  become: true

- name: create ant1 user
  ansible.builtin.user:
    name: ant1
    shell: /bin/bash
    group: ant
    state: present
  become: true

- name: copy ant_static_downloader.sh to remote
  ansible.builtin.template:
    src: ant_static_downloader.py.j2
    dest: /home/ant1/ant_static_downloader.py
    owner: ant1
    group: ant
    mode: '0775'
  become: true
  become_user: ant1

- name: ensure ant users can write to random_verifier metrics directory
  ansible.builtin.file:
    path: "{{ log_path }}/download_files/random_verifier/ant1/"
    state: directory
    mode: '0775'
    owner: ant1
    group: ant
    recurse: yes
  become: true

- name: ensure ant users can write to download_verifier metrics directory
  ansible.builtin.file:
    path: "{{ log_path }}/download_files/download_verifier/ant1/"
    state: directory
    mode: '0775'
    owner: ant1
    group: ant
    recurse: yes
  become: true

- name: ensure ant users can write to performance_verifier metrics directory
  ansible.builtin.file:
    path: "{{ log_path }}/download_files/performance_verifier/ant1/"
    state: directory
    mode: '0775'
    owner: ant1
    group: ant
    recurse: yes
  become: true

- name: ensure ant users can write to downloads directory
  ansible.builtin.file:
    path: "{{ downloads_path }}"
    state: directory
    mode: '0775'
    owner: ant1
    group: ant
  become: true

- name: ensure ant users can write to state directory
  ansible.builtin.file:
    path: "{{ state_path }}"
    state: directory
    mode: '0775'
    owner: ant1
    group: ant
  become: true

- name: ensure the ant users can write to the log output destination
  ansible.builtin.file:
    path: "{{ log_path }}"
    state: directory
    mode: '0775'
    owner: root
    group: ant
  become: true

- name: copy prod.csv file to remote server
  ansible.builtin.copy:
    src: prod.csv
    dest: /home/ant1/prod.csv
    owner: ant1
    group: ant
    mode: '0644'
  become: true

- name: copy manifests directory to remote server
  ansible.builtin.copy:
    src: manifests/
    dest: "{{ manifest_path }}/"
    owner: root
    group: ant
    mode: '0644'
    directory_mode: '0755'
  become: true

- name: Check if systemd ant_random_verifier service file exists
  ansible.builtin.stat:
    path: "/etc/systemd/system/ant_random_verifier.service"
  register: ant_random_verifier_stat

- name: Check if systemd ant_delayed_verifier service file exists
  ansible.builtin.stat:
    path: "/etc/systemd/system/ant_delayed_verifier.service"
  register: ant_delayed_verifier_stat

- name: Check if systemd ant_performance_verifier service file exists
  ansible.builtin.stat:
    path: "/etc/systemd/system/ant_performance_verifier.service"
  register: ant_performance_verifier_stat

- name: create ant_random_verifier systemd service file
  ansible.builtin.template:
    src: ant_random_verifier.service.j2
    dest: "/etc/systemd/system/ant_random_verifier.service"
    owner: ant1
    group: ant
    mode: '0644'
  become: true
  when: not ant_random_verifier_stat.stat.exists

- name: create ant_download_verifier systemd service file
  ansible.builtin.template:
    src: ant_delayed_verifier.service.j2
    dest: "/etc/systemd/system/ant_delayed_verifier.service"
    owner: ant1
    group: ant
    mode: '0644'
  become: true
  when: not ant_delayed_verifier_stat.stat.exists

- name: create ant_performance_verifier systemd service file
  ansible.builtin.template:
    src: ant_performance_verifier.service.j2
    dest: "/etc/systemd/system/ant_performance_verifier.service"
    owner: ant1
    group: ant
    mode: '0644'
  become: true
  when: not ant_performance_verifier_stat.stat.exists

- name: enable ant_random_verifier service
  ansible.builtin.systemd:
    name: ant_random_verifier
    enabled: yes
  become: true

- name: start ant_random_verifier service
  ansible.builtin.systemd:
    name: ant_random_verifier
    state: started
  become: true
  when: start_random_verifier | default(false) | bool

- name: enable ant_delayed_verifier service
  ansible.builtin.systemd:
    name: ant_delayed_verifier
    enabled: yes
  become: true

- name: start ant_delayed_verifier service
  ansible.builtin.systemd:
    name: ant_delayed_verifier
    state: started
  become: true
  when: start_delayed_verifier | default(false) | bool

- name: enable ant_performance_verifier service
  ansible.builtin.systemd:
    name: ant_performance_verifier
    enabled: yes
  become: true

- name: start ant_performance_verifier service
  ansible.builtin.systemd:
    name: ant_performance_verifier
    state: started
  become: true
  when: start_performance_verifier | default(false) | bool

- name: cron job to clean old log directories
  ansible.builtin.cron:
    name: "clean old log directories"
    minute: "*/30"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*"
    user: ant1
    job: "find {{ log_path }} -mindepth 1 -type d -mtime +1 -exec rm -rf {} +"
    state: present
  become: true
