---
public_rpc: False
node_rpc_ip: "127.0.0.1"
node_instance_count: 20
binary_path: /usr/local/bin
antctl_archive_filename: antctl-latest-x86_64-unknown-linux-musl.tar.gz
antctl_archive_url: https://antctl.s3.eu-west-2.amazonaws.com/{{ antctl_archive_filename }}
antctld_archive_filename: antctld-latest-x86_64-unknown-linux-musl.tar.gz
antctld_archive_url: https://antctld.s3.eu-west-2.amazonaws.com/{{ antctld_archive_filename }}
