ant_archive_filename: ant-latest-x86_64-unknown-linux-musl.tar.gz
binary_dir: /usr/local/bin
log_output_dest: /mnt/client/log/uploads
metrics_path: /mnt/client
upload_src_path: /mnt/client/data
upload_batch_size: 16
