---
- name: check if ant binary exists
  ansible.builtin.stat:
    path: "{{ binary_path }}/ant"
  register: ant_binary

- name: download the ant binary
  ansible.builtin.get_url:
    url: "{{ ant_archive_url }}"
    dest: "/tmp/{{ ant_archive_filename }}"
  when: not ant_binary.stat.exists

- name: extract the ant binary to binary directory
  ansible.builtin.unarchive:
    src: "/tmp/{{ ant_archive_filename }}"
    dest: "{{ binary_path }}"
    remote_src: true
  become: true
  when: not ant_binary.stat.exists

- name: create ant group
  ansible.builtin.group:
    name: ant
    state: present
  become: true

- name: create ant1 user
  ansible.builtin.user:
    name: ant1
    shell: /bin/bash
    group: ant
    state: present
  become: true

- name: copy ant_static_uploader.py to remote
  ansible.builtin.template:
    src: ant_static_uploader.py.j2
    dest: /home/ant1/ant_static_uploader.py
    owner: ant1
    group: ant
    mode: '0775'
  become: true
  become_user: ant1

- name: ensure ant users can write to the log output destination
  ansible.builtin.file:
    path: "{{ log_path }}"
    state: directory
    mode: '0775'
    owner: root
    group: ant
  become: true

- name: ensure ant users can write to the metrics directory
  ansible.builtin.file:
    path: "{{ metrics_path }}"
    state: directory
    mode: '0775'
    owner: ant1
    group: ant
    recurse: yes
  become: true

- name: ensure ant users can write to the upload source directory
  ansible.builtin.file:
    path: "{{ upload_src_path }}"
    state: directory
    mode: '0775'
    owner: ant1
    group: ant
    recurse: yes
  become: true

- name: ensure ant users can write to the state directory
  ansible.builtin.file:
    path: "{{ state_path }}"
    state: directory
    mode: '0775'
    owner: ant1
    group: ant
  become: true

- name: Check if systemd ant_static_uploader service file exists
  ansible.builtin.stat:
    path: "/etc/systemd/system/ant_static_uploader.service"
  register: ant_static_uploader_stat

- name: create ant_static_uploader systemd service file
  ansible.builtin.template:
    src: ant_static_uploader.service.j2
    dest: "/etc/systemd/system/ant_static_uploader.service"
    owner: ant1
    group: ant
    mode: '0644'
  become: true
  when: not ant_static_uploader_stat.stat.exists

- name: create the service but allow the user to manually start it
  ansible.builtin.systemd:
    name: ant_static_uploader
    state: stopped
    enabled: yes
  become: true
