---
public_rpc: False
relay: False
node_rpc_ip: "127.0.0.1"
binary_path: /usr/local/bin
# If a custom branch / version is specified, this value must be overwritten.
antnode_archive_url: https://antnode.s3.eu-west-2.amazonaws.com/antnode-latest-x86_64-unknown-linux-musl.tar.gz
antnode_archive_filename: antnode-latest-x86_64-unknown-linux-musl.tar.gz
# If a custom branch is specified, the URL must be changed to 
# "https://sn-node.s3.eu-west-2.amazonaws.com/{org}/{branch}/{bin_name}-{testnet_name}-x86_64-unknown-linux-musl.tar.gz"
# Currently it is done directly inside the code
antctl_archive_filename: antctl-latest-x86_64-unknown-linux-musl.tar.gz
antctl_archive_url: https://antctl.s3.eu-west-2.amazonaws.com/{{ antctl_archive_filename }}
