---
network_dashboard_branch: rc-2024.12.1
network_dashboard_github_url: git@github.com:maidsafe/network-dashboard.git
network_dashboard_repo_path: /root/network-dashboard
network_dashboard_sk_path: /root/.ssh/network-dashboard
